// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badMsg': string;
  'goodMsg': string;
  'mainContainer': string;
  'myAnimation': string;
}
export const cssExports: CssExports;
export default cssExports;
