// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'controlBtn': string;
  'counter': string;
  'disabled': string;
  'discounted': string;
  'hidden': string;
  'img': string;
  'input': string;
  'itemContainer': string;
  'mainContainer': string;
  'onePrice': string;
  'price': string;
  'productArea': string;
  'removeBtn': string;
  'sideBar': string;
  'sideBarBtn': string;
  'subBtn': string;
  'sumPrice': string;
  'title': string;
  'totalPrice': string;
}
export const cssExports: CssExports;
export default cssExports;
