// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'mainContainer': string;
  'msg': string;
}
export const cssExports: CssExports;
export default cssExports;
