// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockContainer': string;
  'disabled': string;
  'hiddenBtn': string;
  'inActiveInput': string;
  'mainContainer': string;
  'penBtn': string;
  'penIcon': string;
  'showBtn': string;
  'textField': string;
  'textInput': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
