const cssClasses = {
  MAIN: "main",
  HEADER: "header",
  FOOTER: "footer",
  CONTAINER_MAIN: "container-main",
  CONTAINER_COLUMN: "container-column",
  CONTAINER_ROW: "container-row",
  CONTAINER_CENTER: "container-center",
  CONTAINER_FORM: "container-form",
  CONTAINER_BUTTONS: "container-buttons",
  BUTTON: "button",
  HEADER_BUTTON: "header-button",
  HEADER_BUTTON_ACTIVE: "header-button-active",
  LOGO: "logo",
  LOGO_IMG: "logo-img",
  TITLE: "title",
  LABEL: "label",
  ERROR: "error",
  DISABLE: "disable",
  INPUT: "input",
  EYE: "eye",
  CONTAINER_INPUTS: "container-inputs",
  LINK: "link",
  CHECKBOX_GROUP: "checkbox-group",
  CHECKBOX_WRAPPER: "checkbox-wrapper",
  CHECKBOX_LABEL: "checkbox-label",
  CONTAINER_NAV: "container-nav",
  CONTAINER_LEFT: "left-container",
  CONTAINER_RIGHT: "right-container",
  IMAGE_CONTAINER: "image",
  IMAGE: "img",
  CARDS: "cards",
  CARD: "card",
  CARD_IMAGE_CONTAINER: "card-image",
  CARD_IMAGE: "card-img",
  CARD_TITLE: "card-title",
  CARD_DESCRIPTION: "card-description",
  CARD_PRICE: "card-price",
  CATEGORY_FILTER: "category-nav",
  CATEGORY_LINK: "category-link",
  CATEGORY_ACTIVE_LINK: "category-link-active",
  CATEGORY_SUB_CONTAINER: "subcategory",
  BREADCRUMBS: "breadcrumbs",
  BREADCRUMB: "breadcrumb",
  BREADCRUMB_ACTIVE: "breadcrumb-link-active",
  PAGINATION_BUTTON: "pagination-button",
  PAGINATION_ACTIVE_BUTTON: "pagination-button-active",
  PAGINATION: "pagination",
  MOBILE_MENU_ITEM: "mobile-li",
  MOBILE_MENU: "mobile-menu",
  BURGER: "burger",
  BURGER_IMG: "burger-img",
  CONTAINER_PRODUCT: "container-product",
  CONTAINER_DESCRIPTION: "container-description",
  SLIDER: "slider-container",
  SLIDER_LIST: "slider-list",
  SLIDER_IMG: "slider-img",
  SLIDER_BTN: "slider-btn",
  SLIDER_PREV: "prev-btn",
  SLIDER_NEXT: "next-btn",
  TEXT: "text",
  SEARCH_BUTTON: "search-button",
  BASKET: "basket",
  CONTROLS: "quantity-controls",
  CONTROLS_CONTAINER: "quantity-wrapper",
  NUMBER: "quantity-number",
};

const Routes = {
  LOGIN: "#login",
  HOME: "#home",
  REGISTRATION: "#registration",
  CATALOG: "#catalog",
  PRODUCT: "#product",
  PROFILE: "#profile",
  BASKET: "#basket",
  ABOUT: "#about",
  NOT_FOUND: "#not-found",
};

const Buttons = {
  LOGIN: "LogIn",
  LOGOUT: "LogOut",
  HOME: "Home",
  CATALOG: "Catalog",
  PRODUCT: "View Details",
  PROFILE: "Profile",
  REGISTRATION: " SignUp",
  GO_LOGIN: "Back to LogIn",
  GO_CATALOG: "Go to Catalog",
  ABOUT: "About us",
  BASKET: "🛒",
};

const Titles = {
  LOGIN:
    "Ready to laugh? Log in with your details and start exploring our sticky notes collection!",
  MAIN: "Log in to start shopping the funniest goods at Joke Store on Sticky Notes!",
  REGISTRATION:
    "Sign up now and let the laughter begin! Create your account and join the joke revolution",
  YEAR: "2025",
  RSSCHOOL: "RS School",
  APP_NAME: "Joke Store",
  CATALOG:
    "From clever code-related puns to subtle observations from therapy sessions, our catalog is full of niche humor crafted for brains like yours. Warning: may cause intellectual giggling",
  HOME: "Hey, ready for some laughs? We’ve got the freshest, sharpest, and laugh-out-loud funniest jokes around 😄 Looking to crack up a friend, a coworker, or just yourself? Dive into the catalog 👀",
  BASKET: "Basket",

};

export { Routes, cssClasses, Buttons, Titles };
